;;; sequence-export-test.el --- Parsed export compatibility -*- lexical-binding: t; -*-
(require 'test-helper)
(require 'xml)

(defun denote-explore-test-export-graph (&optional singleton)
  "Return literal graph so encoder tests do not depend on unfinished assembly."
  (let* ((a (denote-explore-test-id 1)) (b (denote-explore-test-id 2))
         (nodes (list `((id . ,a) (name . "Root") (signature . "1") (type . "org")
                         (filename . "/fixture/root.org") (keywords) (degree . 3)
                         (backlinks . 1) (sequenceMember . t) (contextDistance . 0))))
         (edges nil))
    (unless singleton
      (push `((id . ,b) (name . "External") (signature) (type . "org")
              (filename . "/fixture/external.org") (keywords) (degree . 4)
              (backlinks . 4) (sequenceMember . :json-false) (contextDistance . 1)) nodes)
      (dolist (spec `((,a ,b "hierarchy" 1) (,a ,b "link" 2) (,b ,a "link" 1) (,b ,b "link" 1)))
        (push `((source . ,(nth 0 spec)) (target . ,(nth 1 spec))
                (kind . ,(nth 2 spec)) (weight . ,(nth 3 spec))
                (key . ,(json-encode (vector (nth 2 spec) (nth 0 spec) (nth 1 spec))))) edges)))
    `((meta (type . "Sequence") (directed . t) (parameters "1" 1))
      (nodes . ,nodes) (edges . ,edges))))

(defun denote-explore-test-encode (encoder graph)
  (with-temp-buffer (funcall encoder graph) (buffer-string)))

(ert-deftest denote-explore-export-json-collections-and-booleans ()
  (dolist (singleton '(nil t))
    (let* ((graph (denote-explore-test-export-graph singleton))
           (json (json-parse-string (denote-explore-test-encode #'denote-explore-network-encode-json graph)
                                   :object-type 'alist :null-object :null :false-object :false))
           (nodes (alist-get 'nodes json)) (edges (alist-get 'edges json)))
      (should (vectorp nodes))
      (should (vectorp edges))
      (should (= (length edges) (if singleton 0 4)))
      (should (equal (alist-get 'parameters (alist-get 'meta json)) ["1" 1]))
      (seq-doseq (node nodes) (should (equal (alist-get 'keywords node) [])))
      (unless singleton
        (let ((external (seq-find (lambda (node) (equal (alist-get 'name node) "External")) nodes)))
          (should (eq (alist-get 'sequenceMember external) :false))
          (should (eq (alist-get 'signature external) :null)))))))

(ert-deftest denote-explore-export-gexf-parsed-topology-and-ids ()
  (dolist (singleton '(nil t))
    (let* ((graph (denote-explore-test-export-graph singleton))
           (text (denote-explore-test-encode #'denote-explore-network-encode-gexf graph))
           (xml (with-temp-buffer (insert text) (car (xml-parse-region (point-min) (point-max)))))
           (body (car (xml-get-children xml 'graph)))
           (nodes (xml-get-children (car (xml-get-children body 'nodes)) 'node))
           (edges (xml-get-children (car (xml-get-children body 'edges)) 'edge)))
      (should (= (length nodes) (if singleton 1 2)))
      (should (= (length edges) (if singleton 0 4)))
      (should (equal (xml-get-attribute body 'defaultedgetype) "directed"))
      (let ((ids (mapcar (lambda (edge) (xml-get-attribute edge 'id)) edges)))
        (dolist (id ids) (should (and id (not (string-empty-p id)))))
        (should (= (length (delete-dups ids)) (length edges))))
      (dolist (edge edges)
        (should (member (xml-get-attribute edge 'source) (denote-explore-test-ids graph)))
        (should (member (xml-get-attribute edge 'target) (denote-explore-test-ids graph)))))))

(ert-deftest denote-explore-export-dot-expanded-multigraph ()
  (dolist (singleton '(nil t))
    (let* ((graph (denote-explore-test-export-graph singleton))
           (text (denote-explore-test-encode #'denote-explore-network-encode-graphviz graph))
           (lines (split-string text "\n" t))
           (edges (seq-filter (lambda (line) (string-match-p "^\"[0-9T]+\" -> \"[0-9T]+\" \\[" line)) lines)))
      (should (= (length edges) (if singleton 0 4)))
      (should (string-match-p "URL=\"/fixture/root.org\"" text))
      (dolist (id (denote-explore-test-ids graph))
        (should (string-match-p (regexp-quote id) text))))))

(ert-deftest denote-explore-export-real-template-substitution ()
  (denote-explore-test-with-directory
    (let* ((denote-explore-network-directory denote-directory)
           (denote-explore-network-filename "fixture")
           (denote-explore-network-d3-template (expand-file-name "denote-explore-network.html" denote-explore-test-root))
           (denote-explore-network-d3-js "local-d3.js")
           (file (expand-file-name "fixture.json" denote-directory)) (opened nil))
      (with-temp-file file
        (denote-explore-network-encode-json (denote-explore-test-export-graph t)))
      (cl-letf (((symbol-function 'browse-url-default-browser)
                 (lambda (url &rest _) (setq opened url))))
        (denote-explore-network-display-json file))
      (should (equal opened (expand-file-name "fixture.html" denote-directory)))
      (with-temp-buffer
        (insert-file-contents opened)
        (should-not (string-match-p "{{[a-z-]+}}" (buffer-string)))
        (should (string-match-p "local-d3.js" (buffer-string)))
        (should (string-match-p "20260101T000001" (buffer-string)))))))

(ert-deftest denote-explore-export-other-graphs-baseline ()
  (denote-explore-test-with-directory
    (dolist (n '(1 2))
      (let ((file (denote-explore-test-note n nil (when (= n 1) (denote-explore-test-link 2)))))
        (rename-file file (string-replace ".org" "__alpha_beta.org" file))))
    (let ((denote-explore-network-keywords-ignore nil))
      (dolist (graph (list (denote-explore-network-community-graph "" t)
                          (denote-explore-network-neighbourhood-graph (list (denote-explore-test-id 1) 1) t)
                          (denote-explore-network-keywords-graph 1 t)))
        (should (= (length (alist-get 'nodes graph)) 2))
        (should (= (length (alist-get 'edges graph)) 1))
        (let* ((encoded (denote-explore-test-encode #'denote-explore-network-encode-json graph))
               (parsed (json-parse-string encoded :object-type 'alist)))
          (should (= (length (alist-get 'nodes parsed)) 2))
          (should (= (length (alist-get 'edges parsed)) 1)))
        (should (string-match-p "graph Denote" (denote-explore-test-encode #'denote-explore-network-encode-graphviz graph)))
        (with-temp-buffer
          (insert (denote-explore-test-encode #'denote-explore-network-encode-gexf graph))
          (should (xml-parse-region (point-min) (point-max))))))))

;;; sequence-export-test.el ends here
